const transactions_mappings = {
    'transaction id': 'transactionId',
            'posting date': 'postingDate',
            'effective date': 'effectiveDate',
            'transaction type': 'transactionType',
            'amt': 'amount',
            'check no.': 'checkNumber',
            'ref no.': 'referenceNumber',
            'desc': 'description',
            'transaction cat.': 'transactionCategory',
            'transaction category': 'transactionCategory',
            'typ': 'type',
            'bal': 'balance',
            'memo note': 'memo',
            'ext. description': 'extendedDescription',
            'date': 'postingDate',
            'description': 'description',
            'gross': 'amount',
            'balance': 'balance',
            'time': 'time',
            'time zone': 'timeZone',
            'currency': 'currency',
            'fee': 'fee',
            'net': 'net',
            'from email address': 'emailAddress',
            'name': 'name',
            'bank name': 'bankName',
            'bank account': 'bankAccount',
            'shipping and handling amount': 'shippingAndHandlingAmount',
            'sales tax': 'salesTax',
            'invoice id': 'invoiceId',
            'reference txn id': 'referenceTxnId'
  }
  module.exports = transactions_mappings;